[package]
name = "iron-vault-crypto"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["rlib"]

[dependencies]
k256 = { workspace = true }
ed25519-dalek = { workspace = true }
sha2 = { workspace = true }
sha3 = { workspace = true }
ripemd = { workspace = true }
blake2 = { workspace = true }
hmac = { workspace = true }
pbkdf2 = { workspace = true }
chacha20poly1305 = { workspace = true }
rand = { workspace = true }
bech32 = { workspace = true }
bs58 = { workspace = true }
hex = { workspace = true }
bip39 = { workspace = true }
bip32 = { workspace = true }
rlp = { workspace = true }
thiserror = { workspace = true }
