[package]
name = "iron-vault-ffi"
version.workspace = true
edition.workspace = true

[lib]
name = "iron_vault_crypto"
crate-type = ["cdylib"]

[dependencies]
iron-vault-crypto = { path = "../iron-vault-crypto" }
iron-vault-biz = { path = "../iron-vault-biz" }
hex = { workspace = true }
thiserror = { workspace = true }
zeroize = { workspace = true }

[features]
default = ["all"]
all = ["eth", "sol", "btc", "tron", "sui"]
eth = []
sol = []
btc = []
tron = []
sui = []
